// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHmToJLdBkNsqZc3mb-ZpIBwd3LrzuM0E',
    appId: '1:249484897146:web:8ce0cd08249fe9effa44c3',
    messagingSenderId: '249484897146',
    projectId: 'schmackofatz-787',
    authDomain: 'schmackofatz-787.firebaseapp.com',
    storageBucket: 'schmackofatz-787.firebasestorage.app',
    measurementId: 'G-X16HTQVFJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWTM51VERmYt2IXXjlwZuVukT-ZIopHew',
    appId: '1:249484897146:android:9a3cbe38e4407bd9fa44c3',
    messagingSenderId: '249484897146',
    projectId: 'schmackofatz-787',
    storageBucket: 'schmackofatz-787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArNE7jMhAgy944P-f9qBMWSdjo7_rIFzo',
    appId: '1:249484897146:ios:96872fcf8d8163f9fa44c3',
    messagingSenderId: '249484897146',
    projectId: 'schmackofatz-787',
    storageBucket: 'schmackofatz-787.firebasestorage.app',
    iosBundleId: 'com.example.schmackofatz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArNE7jMhAgy944P-f9qBMWSdjo7_rIFzo',
    appId: '1:249484897146:ios:96872fcf8d8163f9fa44c3',
    messagingSenderId: '249484897146',
    projectId: 'schmackofatz-787',
    storageBucket: 'schmackofatz-787.firebasestorage.app',
    iosBundleId: 'com.example.schmackofatz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHmToJLdBkNsqZc3mb-ZpIBwd3LrzuM0E',
    appId: '1:249484897146:web:47fd8e37cf4f2297fa44c3',
    messagingSenderId: '249484897146',
    projectId: 'schmackofatz-787',
    authDomain: 'schmackofatz-787.firebaseapp.com',
    storageBucket: 'schmackofatz-787.firebasestorage.app',
    measurementId: 'G-NR3P3CQY0Z',
  );

}